# This is a basic workflow to help you get started with Actions

name: Angular-CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout
              uses: actions/checkout@v4

            # Setup nodeJS
            - name: Setup nodejs
              uses: actions/setup-node@v6.3.0
              with:
                  node-version: '22'

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Build app for production
            - name: Build app bundle
              run: npm run build:prod

            # Route file renaming for Github pages
            - name: Rename index for routing
              run: mv dist/demo-elecciones/browser/index.html dist/demo-elecciones/browser/404.html

            # Desploy to Github pages
            - name: Deploy to Pages
              uses: crazy-max/ghaction-github-pages@v5.0.0
              with:
                  build_dir: dist/demo-elecciones/browser
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
